server/db/models/index.js

Model associations for AllstarFull - FieldingPost set up. Hopefully no spelling errors.
close #10

Associations ato f #10

---

server/db/models/index.js
server/db/models/teams.js

Added associations for the models from F-Z listed in the ticket.
close #11

feat(models): add associations for models F-Z

---

CSV/AwardsPlayers.csv

close #19 
added id field and values to the AwardsPlayers CSV file to allow importing of data

refactor(AwardsPlayers): add id field and values to csv

---

CSV/AllstarFull.csv
CSV/BattingPost.csv
CSV/FieldingOFsplit.csv
CSV/FieldingPost.csv
CSV/HomeGames.csv
CSV/Managers.csv
CSV/ManagersHalf.csv
CSV/PitchingPost.csv
CSV/Salaries.csv
CSV/Teams.csv
CSV/TeamsHalf.csv
server/db/models/FieldingOFsplit.js
server/db/models/allstarFull.js
server/db/models/appearances.js
server/db/models/batting.js
server/db/models/battingPost.js
server/db/models/fielding.js
server/db/models/fieldingPost.js
server/db/models/homeGames.js
server/db/models/index.js
server/db/models/managers.js
server/db/models/managersHalf.js
server/db/models/pitching.js
server/db/models/pitchingPost.js
server/db/models/salaries.js
server/db/models/teams.js
server/db/models/teamsHalf.js
server/index.js

refactor(teamName): change team to teamName in csvs and models

---

client/components/navbar.js
client/routes.js
index.css

close #29 
navBar no longer has email and password forms (to be used separately)
navBar is styled and matches wireframe mockup
Next is to add functionality for links and dynamic rendering

Nav bar specializations #29

---

client/components/index.js
client/components/login-form.js
client/components/signUp-form.js
client/routes.js

close #35 
Login and Sign up forms separated out into their own components with index changed for import and export.

Separate auth form #35

---

client/components/auth-form.js
client/components/login-form.js
client/components/signUp-form.js
client/store/user.js

close #34 
Sign up form has fields completed and functional for firstName, lastName, and screenName in addition to email and password.
Correct data posts to database when creating a new user.
Login/auth-form updated to have hardcoded name and display name field titles.

Email sign up form #34

---

client/components/navbar.js

feat(navBar): dynamically render player screen name in nav

---

client/components/signUp-form.js

close #48 
Password confirmation now hides text when typed. 
First name and last name given proper type attributes of text.

feat(signup): set password confirmation box to hide text

---

client/components/signUp-form.js
client/store/user.js
index.css
public/index.html
server/db/models/user.js

close #37 
Field and button locations set to fit mockup (with a few additional changes)
screenName removed and associated screenName issues fixed.

Sign up page styling #37

---

client/components/index.js
client/components/user/LoginForm.js
client/components/user/PlayerInfo.js
client/components/user/SignUpForm.js
client/routes.js
client/store/user.js
index.css
server/api/users.js

Setup backend put route for editing a user.
Create PlayerInfo component and frontend route.
Implement PlayerInfoThunk in store.
close #42

Initial player info #42

---

client/components/user/PlayerInfo.js
client/store/user.js

Created error handling action type for user store.
Proper error message for duplicate screen name now renders without leaving the player info page.
close #56

feat(playerInfo): create dupe screen name error handling action

---

package-lock.json
package.json
server/auth/index.js
server/db/db.js
server/db/index.js
server/db/models/user.js

Created a pre-validation hook to set the screen name to firstname + lastname if the incoming screen name is null.
Updated post route error handling to create a unique screen name using first name, last name and 5 random digits, if the incoming screen name was not unique.
close #43

Default screen name #43

---

client/components/landing/LandingContainer.js
client/components/landing/LandingPres.js
client/components/landing/LoginToPlayPres.js
client/components/user/PlayerInfo.js
index.css

Created and styled landing page login/signup component which will only render when there is no current user. 
Game choice component will render in it's place when a user is logged in.
close #66

Login signup component #66

---

client/components/user/LoginForm.js
client/components/user/SignUpForm.js
index.css

Updated the layout of the Login page to match the style of the Sign Up page.
close #51

Format login page #51

---

server/db/models/game.js
server/db/models/index.js

Created Game model in the database
close #72

feat(gameModel): create initial fields

---

server/api/games.js
server/api/index.js

Implemented and tested the backend post route to create new game instances.
close #74

feat(game): create backend post route

---

server/api/games.js

Installed put route on backend which adds a player to an open game. 
Sets open to false to close a game when the last player is added.
close #75

feat(game): implement initial addplayer to game route

---

client/components/landing/JoinGamePres.js

Fixed null player being added to game issue. 
Player id now being added properly.
close #86

fix(joinGame): new player now added to game instance

---

client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/components/game/IndividualPlayerPres.js
client/components/game/LoadingPres.js
client/store/game.js
server/api/games.js

Created initial components for the gameplay screen. 
Render correct components when game is open/closed.
Render the correct number of players.
close #88 
close #89

Game container #88

---

client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/components/game/IndividualPlayerPres.js
client/components/game/LoadingPres.js
client/store/game.js
index.css

Set up the sidebar to render players and scores just like the wireframe.
close #91

Player sidebar #91

---

client/socket.js
client/store/game.js
server/socket/index.js

When player joins a game they also join a socket room based on the gameID. 
This was done by passing a socket function to the game store.
close #94

feat(socketRooms): join socket room for specific game

---

server/db/models/index.js
server/db/models/question.js
server/index.js

Questions model #99

---

server/db/models/gamePlayer.js
server/db/models/index.js

Created gamePlayer model.
close #100

feat(gamePlayers): create gamePlayers model

---

server/db/models/index.js
server/db/models/playerQuestionResult.js

Created playerQuestionResult model.
close #102

feat(playerQuestionResult): create playerQuestionResult model

---

server/db/models/index.js

Created requested associations.
close #101

feat(associations): associate questions, games, and gameplayers

---

server/db/models/game.js

Removed the player array field from the Game model. 
Added the currentQuestion field.

refactor(game): update model to reflect new design

---

client/components/game/GameContainer.js
client/components/game/IndividualPlayerPres.js
client/components/landing/LandingContainer.js
client/store/game.js
client/store/index.js
client/store/players.js
server/api/games.js
server/db/models/game.js

When a user joins a game, they are added to the list of players in the DB. Which will be kept in the store on the frontend, and displayed in the sidebar to the user.
close #105 
To accomplish this we did the following:
Add Players Store, backend get players route for game instance
Update getGameThunk, backend game put & post routes, gameContainer, indPlayerPres
close #104 
Update Game model so that currentQuestion defaults to 1
close #112

Add user to game player #104

---

client/socket.js
client/store/game.js
server/socket/index.js

Switch open status to false in client store for all players in a game room after the last player joins and the game has been closed on the backend using sockets.
close #118

Game store status update #118

---

designNotes/questionFlow.txt

Added note file for reference detailing the general flow of a game and the flow of the questions.

notes(questionFlow): create notes on game flow and question flow

---

GameplayFunctions/questions/questionGenerator.js
GameplayFunctions/questions/questionHelperFuncs.js
GameplayFunctions/questions/questionOptions.js
GameplayFunctions/questions/questionSkeletons.js

Created initial Question constructor.
Implemented recursive QuestionChoices generator.
Made randomValueSelector helper function.
First pass of interconnected web of option arrays populated with choice objects.
close #122 
close #123

Question framework #122, #123

---

GameplayFunctions/questions/questionGenerator.js
GameplayFunctions/questions/questionOptions.js
GameplayFunctions/questions/questionSkeletons.js

Updated QuestionChoice constructor to create a skeletonKey object with the correct verbiage from the question options object.
Updated the data in the question options objects to have the proper content needed to fill in the question skeleton.
Created the statQuestionSkeleton with variables to match the QuestionChoices object.
close #125

Question skeleton #125

---

GameplayFunctions/questions/content/questionContent.js
GameplayFunctions/questions/questionGenerator.js
designNotes/csvToDB.txt
designNotes/questionFlow.txt
server/api/games.js
server/db/models/batting.js

Created a getter in the batting model that calculates a player's batting average (adjBA) factoring in min qualifying plate appearances for a specific year.
Added Plate Appearances (PA) field into the database.
close #136, #141

Batting model virtual #137

---

server/api/games.js

Created the functionality to generate a correct answer and three other answer choices for player comparison questions.
Updated minPA for single season least stat questions so the query results will filter based on the a particular season's actual minPA.
close #148

Comparison question types #148

---

GameplayFunctions/questions/content/questionOptionsContent.js
server/api/games.js

Created Team stat batting query.
Generated questions based on returned query data.
close #150

Team batting query #150

---

GameplayFunctions/questions/questionGenerator.js
GameplayFunctions/questions/questionHelperFuncs.js
server/api/games.js

Created constructor function in gameplayFunctions directory to generate new question objects.
Refactored code to attach the following methods to the constructor:
-questionTextGenerator method creates question text for the question object
-questionAnswerGenerator method comes up with a set of answers for the question
close #153 
close #154 
close #155

Question constructor function #153

---

GameplayFunctions/questions/content/questionOptionsContent.js
GameplayFunctions/questions/questionGenerator.js

Updated questionAnswerGenerator so that the team comparison questions never display duplicate answers.
close #166

Prevent duplicate answers #166

---

GameplayFunctions/questions/content/questionOptionsContent.js
GameplayFunctions/questions/questionHelperFuncs.js

Add sort for single player derived stat least question. Previously we weren't sorting this type of question, now it is properly sorted in ascending order.
close #167

Sort least derived qs #167

---

designNotes/gameFlow.txt

Add game flow notes for gameplay.

notes(gameFlow): add design notes for gameFlow

---

GameplayFunctions/questions/questionGenerator.js
server/api/games.js

Updated the post route to create the correct number of questions for specified by the game instance.
Added a question number when creating each question instance.

Create correct num questions #173

---

client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/store/game.js
client/store/index.js
client/store/question.js
client/store/questions.js
server/api/games.js

Created the question store.
Send question data to front end on create questions post route. 
Create the questions when the host's game container mounts.
close #176  
close #177  
close #178

Create question store #176

---

GameplayFunctions/questions/questionGenerator.js
client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/components/landing/LandingContainer.js
client/store/game.js
index.css
package-lock.json
package.json

Displayed the first question and answers on the gameboard screen once all players are in the game.
Added some placeholder styling to make the gameboard resemble the design mockup.
close #180

Display initial question #180

---

client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/store/game.js
client/store/questions.js
server/api/games.js

Gave the answer buttons the functionality to capture an answer value on local state.
Installed a submit button to pass along the answer stored on local state.
close #183 
Created a backend route to get all of the questions for a specified game.
Made a thunk creator to getAllQuestions for a specified game.
Hooked up the game Container to get the game's questions for a player from the store if that player is not the host who generated the questions.
close #184

Get all questions #184

---

client/store/game.js
client/store/questions.js
server/api/games.js
server/db/models/index.js

In the Game put route, Remove gamePlayers from game before sending to frontend.
Update Game get route to only send the needed information, either null or the game id.
close #186 
Pluralized the route URL for the Question routes, and made sure post route and get route urls matched.
close #187 
Changed the association for PlayerQuestionResults to be to Question and not Game
close #188

Updates to Modify what is in the Store

---

client/components/game/GameContainer.js
client/store/index.js

When a player hits submit we do the following:
-Lock in time (currently placeholder) and answer.
-Calculate their score (this is currently under construction).
-Dispatch playerAnswer & playerQuestionResult to store.
close #194

Answer submission dispatches #194

---

client/components/game/GameContainer.js
client/socket.js
server/socket/index.js

Created the sockets to pass a player's submitted answer to all players in a game, including the submitting player. 
When players receive the playerAnswer object it is dispatched to the store. 
Removed the playerAnswer dispatch from the GameContainer since the submitting player dispatches that info when receiving it via the socket.
Implemented a check to see if all players have submitted an answer.
close #198

Socket answer data #198

---

client/components/game/GameContainer.js
client/socket.js
client/store/players.js

Add update functionality to Players in Store.
Updated PlayerAnswer to use playerId instead of userId.
In the receiveAnswer socket, when a round ends we calculate and dispatch new scores for each player.

Update player scores #204

---

client/components/game/IndividualPlayerPres.js

Hooked up the score in the player pres component to display the correct score from the store
close #205

feat(IndividualPlayerPres): display correct score

---

client/components/game/AnswerRevealPres.js
client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/socket.js
index.css

Built out the AnswerReveal component which displays whether the player got the question correct, the correct answer highlighted, and the wrong answers clearly marked as incorrect.
Passed the needed props from GameContainer local state in a correctAnswerObj
Updated CSS naming to keep style consistent between multiple components.
close #210

Answer reveal component #210

---

client/components/game/GameContainer.js
client/components/game/results/ResultsContainer.js

Built a timer to move from the results of the round to the next question.
In moving to the next question:
-Reset/clear the allPlayerAnswers store
-Incremented the currentQuestion
-Updated the round tracking logic
close #216

Go to next question #216

---

client/components/game/GameContainer.js
client/components/game/results/ResultsContainer.js
client/components/game/results/RoundResultsPres.js
index.css

Built out a RoundResults component which has a table with the following:
-Who got the question correct in green and incorrect in red and which answer each player chose
-The score each player earned for that question
-Player results sorted by the scores for that question
-Set time column as a placeholder until it score is calculated using actual time
close #218

Round results component #218

---

client/components/game/GameContainer.js
client/components/game/results/GameOverPres.js

Create an initial GameOver component.
After answering the final question, update finalRound in local state.
If it is the final round, update gameOver in local state.
If the game is over, render the initial GameOver component.
close #220

Display game over #220

---

client/components/game/GameContainer.js
client/components/game/results/GameOverPres.js

The GameOverPres Component now has:
-The final standings.
-A button/link to return to the landing page.
close #221

feat(gameOverPres): add link to return to landing page

---

client/components/game/GameBoardPres.js
client/components/game/GameContainer.js
client/components/game/results/AnswerRevealPres.js
client/components/game/results/ResultsContainer.js
client/components/landing/JoinGamePres.js
index.css

-The submit button is disabled until a player has chosen an answer to prevent them from submitting an empty answer.
-After submit is clicked, the chosen answer is clearly highlighted with the button filled and all the answer buttons are disabled.
-Centered the submit button.
-Added a waiting for players to answer message after a player has submitted their answer.
-Styled the answer reveal buttons.

Submit answer button #199

---

HelperFunctions/utilityFunctions.js
client/components/game/GameContainer.js
client/components/game/results/RoundResultsPres.js
client/components/landing/LandingContainer.js
client/components/user/LoginForm.js
client/components/user/SignUpForm.js
index.css

Locked the navBar at the top of the screen, so that it stays visible when the content of any page is scrolled.
Set up onLoad functionality to get each page to start on the top.
close #228

Nav Bar - Lock at top of screen #228

---

client/components/game/GameContainer.js
client/components/game/gameBoard/GameBoardPres.js
client/components/game/gameBoard/GameBoardScoringTimer.js
client/components/game/results/GameOverPres.js
index.css
package-lock.json
package.json

Created a GameBoardTimerBar component which starts when the countdown ends and captures a time when the player submits their answer.
Implemented the scoring for the timed round gametype based on the time taken to answer a question.
close #234

Scoring timer #234

---

client/components/game/GameContainer.js
client/components/game/IndividualPlayerPres.js
client/components/game/results/AnswerRevealPres.js
client/components/game/results/GameOverPres.js
client/components/game/results/ResultsContainer.js
client/components/game/results/RoundResultsPres.js
index.css

Styled the sidebar:
-narrowed the width
-changed the layout of IndividualPlayerPres component
-highlighted the user's own player pres component (only for multiplayer games)
-prevented the sidebar from changing width between components

Style sidebar #244

---

GameplayFunctions/questions/content/questionContent.js
GameplayFunctions/questions/content/questionOptionsContent.js
GameplayFunctions/questions/questionGenerator.js
client/components/game/GameContainer.js
client/socket.js
client/store/game.js
client/store/players.js
client/store/questions.js
package.json
server/api/games.js
server/api/users.js
server/index.js
server/socket/index.js
testsBaseballData/dbQueries/battingData.spec.js

Created the test-baseball db framework to be used to test the Layman Baseball data.
Created tests using that framework.
Analyzed the results of the test to identify where the question creation process needed to be modified to account for the data coming back.
This included the following modifications:
-Removed the question creation route and tied its functionality to game creation.
-Updated conditionals in the api and in the questionGenerator function that test the validity of the question and its answers.
-Implemented recursive functionality in the creation of questions to rerun the conditionals each time we need to pick a different year.
-Keep track of the number of questions created, and pass it to everyone in the game using sockets.
*Once the correct number of questions have been …

Batting stat query update #246

---

client/components/navbar.js
client/components/user/LoginForm.js
client/components/user/SignUpForm.js
index.css
package-lock.json
package.json

Disabled links for Stats, Google and Facebook (login and signup).
Added Coming Soon tooltips to each of these.
close #258

Coming soon tool tips #258

---

package.json

Add deployment script for heroku.
close #260

feat(deploy): add deployment script

---

client/components/user/PlayerInfo.js
client/components/user/SignUpForm.js
public/index.html
server/auth/google.js
server/db/models/user.js

Enabled a user to sign up using a Google account.
Once a user signs up through Google, they are redirected to the player-info page where they choose a screen name and player image.
Updated creation of default screen name.

Enable google o auth #265

---

client/components/navbar.js

linked up screenName to PlayerInfo component
close #268

feat(navbar): link up screenName to PlayerInfo

---

client/components/user/PlayerInfo.js
designNotes/csvToDB.txt
server/auth/google.js
server/db/models/gametype.js
server/db/models/user.js

If account was created through google, allow the user to select their google profile image as their player image.
When on the profile page, the user's profile image radio button is checked by default.
close #269

Select google image #269

---

server/auth/google.js

make the profileImage the default playerImage
#269 
#271

refactor(google): make the profileImage the default playerImage

---

client/app.js
client/components/footer.js
client/components/index.js
index.css

Created a footer component which includes: 
-credit/legal info for the Lahman Baseball Database
-a byline and email to reach us
-art asset credits
Locked the footer at the bottom of the screen.

Implement footer component #273

---

client/app.js
index.css

fixed footer in proper place so it no never floats above the bottom of the window 
avoid content overlap between the footer and gametypes

fix(indexCSS): fix footer in proper place, avoid content overlap

---

index.css

Reduced the space between lines of the Landing Pres Text
close #284

style(landingText): reduce space between lines of text

---

package-lock.json
package.json
server/api/gamePlayer.js
server/api/games.js
server/api/users.js
server/auth/google.js
server/index.js

Updated npm packages:
-webpack cli v 3.2.0
-connect-session-sequelize v6.0.0
-sequelize v5.3.0 (required changes to findById => findByPk, find => findOne)
close #288

Update sequelize #288

---

GameplayFunctions/questions/questionCreatorFunc.js
server/api/games.js

Updated questionCreatorFunc to be reusable function and relocated it from the games api to the GameplayFunctions directory.
close #293

Modularize games api #293

---

scripts/seedBaseballData

Add conditionals for testing on both of our machines.

add envs to testing seed script
